---
- name: Install application
  hosts: all
  become: yes

  vars:
    app_name: stress
  
  tasks:
  
  - name: Install application
    yum: name={{ app_name }} state=installed
        
#  - name: Start. And make autostart after reboot
#    service: name={{ app_name }} state=started enabled=yes
