---
- name: Ansible Lesson 10 Errors_Handling
  hosts: all
  any_errors_fatal: true
  become: yes


  tasks:
  - name: Task Number1
    yum: name=treeee state=latest
    ignore_errors: yes

  - name: Task Number2
    shell: echo Hello World!!
    register: results
#    failed_when: "'World' in results.stdout"
#    failed_when: results.rc == 0
    

  - debug:
        var: results

  - name: Task Number3
    shell: echo Privet Mir!!

